project:
  type: website
  output-dir: C:/Users/eron.stu/OneDrive - UBC/Documents/GitHub/E-Portfolio

website:
  title: "Eron's E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: content.qmd
        text: Projects
      - href: Contact Me.qmd
        text: Contact Me

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

