---
title: "Resume"
---

# Education

-   **Masters of Geomatics for Environmental Management**

    Faculty of Forestry, University of British Columbia  \| April, 2025

-   **Bachelor of Science in Marine Ecology**

    College of the Environment, Western Washington University \| December, 2018

# Experience

**Biological Science Technician 2, Full Time \$25(US)/HR**

Washington Department of Fish and Wildlife - Bellingham, WA. \| March 2023-August 2024

Owen Donohoe (978) 766-7882, [Owen.Donohoe\@dfw.wa.gov](mailto:Owen.Donohoe@dfw.wa.gov)

-   Created potential spawning ground habitat maps using ArcGIS Pro for areas not currently surveyed using existing spawning ground data.

-   Conducted comprehensive salmon and steelhead spawning ground, fish abundance and presence surveys by walking or rafting streams and rivers

-   Identified, counted and marked over 1,500 redds using ArcGIS Pro, R and excel to create spatial maps representing spawning ground locations for seven species of fish

-   Utilized maps and graphs created with R and ArcGIS to determine current and future salmon/steelhead runs in order to set local recreational fishing seasons and regulations

-   Collected biological samples from live and dead salmonids including species type, DNA, scales, lengths, weights, sex, otoliths and CWT’s

**Biological Science Technician 2, Full Time \$22(US)/HR**

Washington Department of Fish and Wildlife - La Conner, WA. \| March 2022-February 2023

Justin Spinelli (425) 739-1024, [Justin.Spinelli\@dfw.wa.gov](mailto:Justin.Spinelli@dfw.wa.gov)

-   Conducted standard lake surveys via boat electrofishing, gillnets and fyke nets on washington lakes to determine biodiversity

-   Independently worked on field research in diverse and unpredictable terrain and conditions 

-   Transported, floy tagged and released mature rainbow trout for recreational fishing

-   Independently maintained, trailered, launched and operated boats 19ft. and 26ft long to conduct creel surveys on local lakes

-   Identified and biosampled warm water species including walleye, kokanee, rainbow, browntrout, cutthroat, yellow perch, burbot, whitefish, bullhead, crappie, rockbass, bass including sex, length, marks, scales, GSI, otoliths, and genetic samples

-   Extracted stomach samples from yellow perch, rock bass and walleye to determine salmonid predation rates

-   Conducted creel surveys to obtain efficacy of liberalized regulations

-   Captured white crappie vie fyke nets and transported to reintroduce self-sustaining population for recreational fishery 

-   Transported and Spawned adult chum salmon

**Biological Science Technician 2 - Smolt Trapping, Full Time \$22(US)/HR**

Washington Department of Fish and Wildlife - Twisp, WA. \| November 2021-December 2021

Nathaniel Fuchs (760) 660-8120, [Nathaniel.Fuchs\@dfw.wa.gov](mailto:Nathaniel.Fuchs@dfw.wa.gov)

-   Determine overall outmigration of salmonid smolt populations to calculate mortality rates associated with dams to predict future adult returns

-   Captured, identified, biosampled and PIT-tagged juvenile/adult ESA-listed salmonids and fish species in North Central Washington rivers via rotary screw trap

-   Assisted with in-stream installation, removal, and repair of juvenile screw trap

-   Monitored and operated screw trap based on real-time observations and forecasted environmental conditions, including flood events

-   Entered, managed and uploaded juvenile PIT tagging files into P4 to conduct queries in PTAGIS and Access databases

-   Performed quality assurance and quality control checks on collected data 

**Biological Science Technician 2 - Creeler, Full Time \$22(US)/HR**

Washington Department of Fish and Wildlife - Twisp, WA. \| August 2021-October 2021

Ryan Fortier (509) 720-6424, [Ryan.Fortier\@dfw.wa.gov](mailto:Ryan.Fortier@dfw.wa.gov)

-   Biosampled summer Chinook including sex, length, marks, scales, and genetic samples

-   Dissected and read coded wire tags collected from Columbia River creel surveys to determine origin of fish

-   Conducted creel surveys to obtain catch number and effort at Columbia and Methow River fishing locations

-   Accurately recorded and entered all data associated with surveys of the fishery

-   Identified freshwater and anadromous fish species in eastern Washington caught in screw trap, including but not limited to spring/summer Chinook, rainbow/steelhead trout, Coho, Sockeye, whitefish, Bull trout, Westslope cutthroat, etc

-   Aided in lake rehabilitation including the application of rotenone to eliminate invasive species

**Biological Science Technician, Full Time \$14(US)/HR**

US Fish and Wildlife Service - Winthrop, WA. \| March 2021-June 2021

Michael Humling (509) 423-0533, [Michael.Humling\@usda.gov](mailto:Michael.Humling@usda.gov)

-   Created fish presence maps via ArcGIS to aid in collection of steelhead broodstock

-   Identified, PIT-tagged, Floy-tagged, and biosampled adult steelhead trout

-   Collected adult steelhead broodstock via weir traps, hatchery outfalls, and angling

-   Conducted steelhead spawning ground surveys

-   Sampled juvenile salmonids via backpack electrofishing with the Yakama tribe.

-   Performed gonadosomatic index (GSI) sampling of hatchery spring Chinook and steelhead after volitional releases to determine sexual maturity

-   Gained extensive knowledge of P4, PTAGIS, HPR PIT Tag readers and CWT detectors

-   Aided in live-spawning of steelhead and transfer to the kelt reconditioning program

**Commercial Salmon Fisherman - Deck Boss / Relief Captain, Full Time 30K(US)/YR**

Snag Fisheries/Silver Bay Seafoods - Bristol Bay, AK \| June-August 2005-2021

Eric Marble (360) 391-4155, [Eric.Marble\@ymail.com](mailto:Eric.Marble\@ymail.com)

-   Communicated with biologists to create an interface between fishermen and scientists

-   Enforced sustainable regulations within crew

-   Ran and performed maintenance on hydraulic, electrical, and mechanical machinery as well as repairing fishing nets

-   Managed a crew in a fast paced and unpredictable environment

-   Planned daily fishing operations by identifying the best fishing grounds and assessing the current weather, tides and sea conditions

-   Recruited, evaluated and hired crewmen for fishing seasons

**Commercial Crabber -Deck Boss, Full Time 10K(US)/YR**

Whitlock and Sons Fisheries INC. - Puget Sound/Salish Sea, WA. \|  October-April 2016-2021

Spencer Whitlock (425) 530-5953, [Pugetsoundcrab\@gmail.com](mailto:Pugetsoundcrab@gmail.com)

-   Advocated with local board of fisheries and tribal members for a fair and sustainable quota

-   Proficient with navigational equipment

-   Analyzed weather and habitat conditions to create maps predicting crab movement and presence

-   Identified and measured catch to determine whether they meet legal size requirements and released all bycatch

-   Worked as part of an efficient team in close quarters for extended periods of time

# Awards & Honors

-   BENJAMIN A. GILMAN INTERNATIONAL SCHOLARSHIP
-   IIE GENERATION STUDY ABROAD SCHOLARSHIP
-   DEAN'S HONORS LIST

# Teaching Assistantships

-   List any TA positions you may have held.

# Institutional Service

-   Volunteering etc.
